name: Ping the database every hour to prevent it from sleeping

on:
  schedule:
    - cron: '0 * * * *'
jobs:
  ping:
    name: Ping database
    runs-on: ubuntu-latest
    steps:
      - name: cURL request
        run: curl https://acm-registration.netlify.app/api/ping
